desarrollodoc/desarrollodoc/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from core.views import index, ProyectoListView, ProyectoDetailView, ProyectoCreate, ProyectoUpdate, ProyectoDelete, \
DesarrolloUpdate, DesarrolloCreate, DesarrolloDelete, busqueda

urlpatterns = [
    url(r'^$', index, name='index'),
    path('proyectos/', login_required(ProyectoListView.as_view()), name='proyectos'),
    path('proyecto/<int:pk>/', login_required(ProyectoDetailView.as_view()), name='proyecto-detail'),
    path('create/', login_required(ProyectoCreate.as_view()), name='proyecto_create'),
    path('nuevodesarrollo/<int:proyecto_id>/', login_required(DesarrolloCreate.as_view()), name='desarrollo_create'),
    path('editarproyecto/<int:pk>/', login_required(ProyectoUpdate.as_view()), name='proyecto_update'),
    path('editardesarrollo/<int:pk>/', login_required(DesarrolloUpdate.as_view()), name='desarrollo_update'),
    path('eliminar/<int:pk>/', login_required(ProyectoDelete.as_view()), name='proyecto_delete'),
    path('eliminardesarrollo/<int:pk>/', login_required(DesarrolloDelete.as_view()), name='desarrollo_delete'),
    url(r'^filtro/$', busqueda, name='proyecto_busqueda'),
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

desarrollodoc/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Proyecto(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='Nombre del Proyecto')
    modulo = models.CharField(max_length=50, verbose_name='Módulo')
    descripcion = models.TextField(max_length=1500, verbose_name='Descripción')
    notas = models.TextField(max_length=1500, verbose_name='Notas')
    creado = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    actualizado = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')
    #creado_por = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuario de creación')

    def __str__(self):
        return '{} {}'.format(self.nombre, self.modulo)


class Desarrollo(models.Model):
    version = models.CharField(max_length=50, verbose_name='Versión')
    consultas = models.TextField(max_length=1500, verbose_name='Consultas Relevantes')
    informacion = models.TextField(max_length=1500, verbose_name='Información del proyecto')
    proyecto = models.ForeignKey(Proyecto, null=True, on_delete=models.SET_NULL)

    DESA_STATUS = (
        ('t', 'Terminado'),
        ('d', 'En Desarrollo'),
        ('p', 'Pausado'),
        ('c', 'Cancelado'),
    )

    estatus = models.CharField(max_length=1, choices=DESA_STATUS, blank=True, default='d', help_text='Avance del Desarrollo')
    creado = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    actualizado = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')

    class Meta:
        ordering = ["-creado"]

    def __str__(self):
        return '{} {}'.format(self.id,self.proyecto.nombre)

desarrollodoc/core/forms.py
from django import forms

from .models import Proyecto, Desarrollo


class ProyectoForm(forms.ModelForm):

    class Meta:
        model = Proyecto

        fields = [
            'nombre',
            'modulo',
            'descripcion',
            'notas',
        ]
        labels = {
            'nombre': 'Nombre',
            'modulo': 'Módulo',
            'descripcion': 'Descripción',
            'notas': 'Notas',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'modulo': forms.TextInput(attrs={'class':'form-control'}),
            'descripcion': forms.Textarea(attrs={'class':'form-control'}),
            'notas': forms.Textarea(attrs={'class':'form-control'}),
        }


class DesarrolloForm(forms.ModelForm):

    class Meta:
        model = Desarrollo

        fields = [
            'proyecto',
            'version',
            'consultas',
            'informacion',
            'estatus',
        ]
        labels = {
            'proyecto': 'Proyecto del Desarrollo',
            'version': 'Versión',
            'consultas': 'Consultas Relevantes',
            'informacion': 'Información',
            'estatus': 'Status',
        }
        widgets = {
            'proyecto': forms.Select(attrs={'class':'form-control'}),
            'version': forms.TextInput(attrs={'class':'form-control', 'readonly':'readonly'}),
            'consultas': forms.Textarea(attrs={'class':'form-control'}),
            'informacion': forms.Textarea(attrs={'class':'form-control'}),
            'estatus': forms.Select(attrs={'class':'form-control'}),
        }

desarrollodoc/core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from core.models import Proyecto, Desarrollo
from core.forms import ProyectoForm, DesarrolloForm

import itertools
import string

from django.db.models import Max

# Create your views here.
def index(request):
    return render(request, 'core/index.html')


class ProyectoListView(ListView):
    model = Proyecto
    paginate_by = 10
    template_name = 'core/proyecto_list.html'


class ProyectoDetailView(DetailView):
    model = Proyecto


class ProyectoCreate(CreateView):
    model = Proyecto
    form_class = ProyectoForm
    template_name = 'core/proyecto_form.html'
    success_url = reverse_lazy('proyectos')


class DesarrolloCreate(CreateView):
    model = Desarrollo
    form_class = DesarrolloForm
    template_name = 'core/desarrollo_form.html'     

    def get_initial(self):
        initials = super(DesarrolloCreate, self).get_initial()
        initials['proyecto'] = self.kwargs['proyecto_id']
        a= list(map('.'.join, itertools.product(string.digits, repeat=4)))
        b = Desarrollo.objects.filter(proyecto_id=self.kwargs['proyecto_id']).first()
        if b is None:
            b = Desarrollo()
            b.version = '1.0.0.0'
        c = b.version
        d = c.replace('.', '')
        initials['version'] = a[int(d)+1]
        return initials

    def get_success_url(self):
        return reverse_lazy('proyecto-detail', kwargs={'pk': self.kwargs['proyecto_id']})


class ProyectoUpdate(UpdateView):
    model = Proyecto
    form_class = ProyectoForm
    template_name = 'core/proyecto_form.html'
    #success_url = reverse_lazy('proyectos')

    def get_absolute_url(self):
        return reverse('proyecto_busqueda', kwargs={'nombre': self.nombre})


class DesarrolloUpdate(UpdateView):
    model = Desarrollo
    form_class = DesarrolloForm
    template_name = 'core/desarrollo_form.html'
    
    def get_success_url(self):
        return reverse_lazy('proyecto-detail', kwargs={'pk': self.get_object().proyecto_id})


class ProyectoDelete(DeleteView):
    model = Proyecto
    template_name = 'core/proyecto_delete'
    success_url = reverse_lazy('proyectos')


class DesarrolloDelete(DeleteView):
    model = Desarrollo
    template_name = 'core/desarrollo_delete.html'

    def get_success_url(self):
        return reverse_lazy('proyecto-detail', kwargs={'pk': self.get_object().proyecto_id})


def busqueda(request):
   q = request.GET.get('q','')
   proyectos = Proyecto.objects.filter(nombre__icontains=q)
   return render(request, 'core/proyecto_busqueda.html', {'proyectos': proyectos})

desarrollodoc/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>

    {% block extrastatic %}
    {% endblock %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <title>{% block title %} Document {% endblock %}</title>
</head>
<body>
<div class="container">
    {% block navbar %}
    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                               <a class="navbar-brand" href="#">DOCUMENTO DE DESARROLLO</a>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Módulos<span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{% url 'proyectos' %}">Proyectos</a></li>
                                        </ul>
                                    </li>
                                </ul>
                                <ul class="nav navbar-nav navbar-right">
                                    {% if user.is_authenticated %}
                                    <li>
                                        <a href="{% url 'logout'%}?next={{request.path}}" role="button" aria-expanded="false">Logout</a>
                                    </li>
                                    {% else %}
                                    <li>
                                        <a href="{% url 'login'%}?next={{request.path}}" role="button" aria-expanded="false">Login</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    {% endblock%}

    {% block header%}
    {% endblock%}

    {% block content %}

    {% endblock %}

    {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" >previous</a>
            {% endif %}
              <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
            {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" >next</a>
            {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

    {% block footer %}
    {% endblock %}
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block extrajs %}
    {% endblock %}

</body>
</html>

desarrollodoc/templates/core/confirm_delete.html
{% extends "base/base.html" %}

{% block content %}

<h1>Borrar Proyecto</h1>

<p>Está seguro de borrar el Proyecto?: {{ proyecto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

desarrollodoc/templates/core/desarrollo_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el Desarrollo con esta versión: {{ object.version }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'proyectos' %}">Cancelar</a>
</form>
{% endblock %}

desarrollodoc/templates/core/desarrollo_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class=""row>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.proyecto.name }}">{{ form.proyecto.label }}</label>
                {{ form.proyecto }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.version.name }}">{{ form.version.label }}</label>
                {{ form.version }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.consultas.name }}">{{ form.consultas.label }}</label>
                {{ form.consultas }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.informacion.name }}">{{ form.informacion.label }}</label>
                {{ form.informacion }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.estatus.name }}">{{ form.estatus.label }}</label>
                {{ form.estatus }}
            </div>
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Guardar</button>
        </div>
    </div>
</form>
{% endblock %}

desarrollodoc/templates/core/index.html
{% extends 'base/base.html' %}

{% block title %}
DOCUMENTO DE DESARROLLO
{% endblock %}

{% block header %}

{% endblock %}

desarrollodoc/templates/core/proyecto_busqueda.html
{% extends 'base/base.html' %}

{% block content %}
<table class="table table-striped">
    <tr>
        <td><strong>Nombre</strong></td>
        <td><strong>Módulo</strong></td>
        <td><strong>Descripción</strong></td>
        <td><strong>Notas</strong></td>
        <td><strong>Fecha de Creación</strong></td>
    </tr>
    {% for proyecto in proyectos %}
    <tr>
        <td>{{ proyecto.nombre }}</td>
        <td>{{ proyecto.modulo }}</td>
        <td>{{ proyecto.descripcion }}</td>
        <td>{{ proyecto.notas }}</td>
        <td>{{ proyecto.creado }}</td>
        <td>
            <a href="{% url 'proyecto-detail' proyecto.pk %}" class="btn btn-primary">Detalles</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

desarrollodoc/templates/core/proyecto_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'core:proyectos' %}">Cancelar</a>
</form>
{% endblock %}

desarrollodoc/templates/core/proyecto_detail.html
{% extends "base/base.html" %}

{% block content %}
  <h1>Nombre: {{ proyecto.nombre }}</h1>

  <p><strong>Módulo:</strong> {{ proyecto.modulo }}</p>
  <p><strong>Descripción:</strong> {{ proyecto.descripcion }}</p>
  <p><strong>Notas:</strong> {{ proyecto.notas }}</p> 
  <p><strong>Creado por:</strong> {{ proyecto.creado_por }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <div class="text-right">
      <a href="{% url 'desarrollo_create' proyecto.pk %}" class="btn btn-primary" role="button">Crear Desarrollo</a>
    </div>
    <hr>
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <td>#</td>
          <td>Versión</td>
          <td>Consultas Relevantes:</td>
          <td>Información del Desarrollo:</td>
        </tr>
      </thead>
      <tbody>
        {% for detalle in proyecto.desarrollo_set.all %}
        <tr>
          <td>{{detalle.id}}</td>
          <td>{{ detalle.version}}</td>
          <td>{{ detalle.consultas}}</td>
          <td>{{ detalle.informacion}}</td>
          <td>
            <a class="btn btn-primary" href="{% url 'desarrollo_update' detalle.id %}">Editar</a>
            <a class="btn btn-danger" href="{% url 'desarrollo_delete' detalle.id %}">Eliminar</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

desarrollodoc/templates/core/proyecto_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<div class=""row>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.nombre.name }}">{{ form.nombre.label }}</label>
				{{ form.nombre }}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.modulo.name }}">{{ form.modulo.label }}</label>
				{{ form.modulo }}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.descripcion.name }}">{{ form.descripcion.label }}</label>
				{{ form.descripcion }}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.notas.name }}">{{ form.notas.label }}</label>
				{{ form.notas }}
			</div>
		</div>
	</div>
    <div class="col-md-8 col-md-offset-2">
		<div class="form-group">
			<button class="btn btn-primary" type="submit">Guardar</button>
		</div>
	</div>
</form>
{% endblock %}

desarrollodoc/templates/core/proyecto_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Lista de Proyectos</h1>
    <div class="text-right">
        <form action="{% url 'proyecto_busqueda' %}" method="GET">
            <input type="text" name="q" placeholder="Buscar Proyecto" />
            <input type="submit" class="btn btn-primary" value="Buscar" />
        </form>
    </div>

    <hr>
    {% if object_list %}
    <ul>
        {% for proyecto in object_list %}
        <div class="list-group">
            <a href="{% url 'proyecto-detail' proyecto.pk %}" class="list-group-item active">
              <h4 class="list-group-item-heading">{{ proyecto.nombre }}</h4>
              <p class="list-group-item-text">{{ proyecto.modulo }}</p>
            </a>
          </div>
        {% endfor %}
    </ul>
    {% else %}
        <P>No existen proyectos dados de alta</P>
    {% endif %}
    <hr>
    <p><a href="{% url 'proyecto_create' %}" class="btn btn-primary" role="button">Crear Proyecto</a></p>
{% endblock %}